version: '3.8'

services:
  postgres:
    container_name: PortContainer
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mareen
      - POSTGRES_PASSWORD=Kalamaja1
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5444:5432"
    volumes:
      - SELECTED_NAME-postgres-volume:/var/lib/postgresql/data

volumes:
  SELECTED_NAME-postgres-volume: